-- https://www.hackerrank.com/challenges/the-pads/problem
-- The PADS

SELECT CONCAT(NAME, '(', SUBSTR(OCCUPATION, 1, 1), ')') AS OUTPUT
FROM OCCUPATIONS
ORDER BY NAME;

SELECT CONCAT('There are a total of ', COUNT(OCCUPATION), ' ', LOWER(OCCUPATION), 's.') AS OUTPUT
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION;